### ISSUE TITLE
Is there a way to make the downloads optional? (prompted?)

### ISSUE THREAD

**Issue by stephantual** [piyushK52/comfy-runner#4]
hello! Very cool stuff and very much needed given how fast thigns are moving (Svd img2vid 1.1 just came out this am).

Quick q: is there a way to tell comfy runner to execute step by step and prompted? 
For example, it could warn you: "checkpoint xyz is missing, do you want to download it? "

reasons include:
a) files tend to be extremely large
b) sometimes someone will push a worflow and include the 'wrong' models - this is seen with ipadapter for example where you had 2 alternatives to face ID come out in a week straight, forcing Youtubers who make tutorials to redo their videos and even the node creators to re-engineer their solutions.

Thank you!

**Comment by piyushK52** [comment]
Hey Stephan! do you mean to say that you won't run the workflow if it has to download large files? (because the workflow won't run if any model is missing)

**Comment by stephantual** [comment]
Kinda, let me give you a practical example: 

![image](https://github.com/piyushK52/comfy-runner/assets/1596070/e117d9ad-fa04-482a-a86b-2e6a7fad6296)

Here you can see that ui manager thinks i dont have the model, when in fact i do. Runner behaves the same way. The models are there, they are just named one character differently in a different subfolder than the one expected.

So i wouldn't want to download a model twice just because i put it in the 'wrong' folder. 

Also bonus question how fast is the model db updated? for example svd-xl imgtovid 1.1 just came out 8h ago, how does comfyrunning track these releases?

Thank you :)

**Comment by piyushK52** [comment]
Ah got it.. will add an option for this. Right now I haven't put much thought into updating the data files. Currently, the model list is loaded from Comfy-manager and the models in the 'data' folder. You can wait for the models to be added in CM if they are popular enough or you can raise PRs here if you want. In the long term, I think a simple db/repository/website makes sense where people just list their models and the huggingface links (as civit is the only alternative rn and they severely limit the download speeds of unpopular models)

**Comment by stephantual** [comment]
Thank you @piyushK52 ! Good stuff!
